### PR TITLE
Integrations links in header and footer update

### PR DESCRIPTION
**Pull request by teallarson**
First round -- I went with the exact phrasing that the SEO firm recommended ("data integration" for Salesforce and "integration" for all others) and I don't hate it as much as I thought I would visually.

Though from a user experience perspective, I would expect different phrasing to mean different behavior, so that may be confusing.

Victorious suggested this change because it will make our anchor texts match the intention for those pages.  The reason they are different is that people search for "Salesforce data integration" much more than "Salesforce integration", but the others are vice versa.

Open to alternatives, or to giving this a try and trusting it will help!

### CODE REVIEW

**Review by evantahler — COMMENTED** [review]
The changes look fine to me technically.  Visually... it's rather wordy to me now... but, that's the game we are playing!  I defer to @tealjulia and @andyjih when it comes to content.

Screen Shot 2021-07-12 at 3 06 45 PM

On mobile, each link is multi-line now.  Perhaps the layout could shift to stack the columns to each line has more horizontal space?

Screen Shot 2021-07-12 at 3 08 51 PM

**Comment by teallarson** [comment]
> On mobile, each link is multi-line now. Perhaps the layout could shift to stack the columns to each line has more horizontal space?
> 

I'll take care of that scary mobile layout before merging for sure.  I peeked at a number of other sites' footers and they also seem to be playing the SEO keyword game, so I'm going with it.

**Review by andyjih — APPROVED** [review]
👍  And +1 to stacking the footer in mobile views. Nice work!

**Review by evantahler — APPROVED** [review]
Nice!

Screen Shot 2021-07-13 at 11 47 57 AM

**Pull request merged**
