### PR TITLE
Trying node v15

### PR DESCRIPTION
**Pull request by bleonard**
Trying to use v15 locally (Mac M1!), but Vercel does not support it yet.
The tests and github actions and prod/previews still run 14, so I want to see if this works.

It seems to be ok.

### CODE REVIEW

**Comment by bleonard** [comment]
Screen Shot 2021-03-14 at 3 57 28 PM

**Comment by bleonard** [comment]
Also

Screen Shot 2021-03-14 at 4 00 53 PM

**Comment by bleonard** [comment]
Vercel trying to make lockfile v2 work.
Seems to be ok.

Screen Shot 2021-03-14 at 4 06 06 PM

**Comment by evantahler** [comment]
I rebased from `main` and removed the `engines` section from `package.json` - since we set the node version explicitly with vercel, and this package isn't shared,  it's not needed there

**Pull request merged**
