### PR TITLE
Blog post: Ignoring variables when destructuring arrays

### PR DESCRIPTION
**Pull request by pedroslopez**

### CODE REVIEW

**Comment by evantahler** [comment]
@pedroslopez looking good!  I re-ran your test and everything is OK!  Looks like there was a timeout in CI or something silly...

**Comment by evantahler** [comment]
@pedroslopez are you ready for this to be merged in?

**Comment by pedroslopez** [comment]
> @pedroslopez are you ready for this to be merged in?

I believe so! Let me know if there's anything I should change or do differently

**Comment by evantahler** [comment]
It's great! Welcome to the blog!

**Pull request merged**
