### PR TITLE
Update Footer CTA to "pop"

### PR DESCRIPTION
**Pull request by evantahler**
Extracted from https://github.com/grouparoo/www.grouparoo.com/pull/564

The Footer CTA was getting a bit lost on some of the docs pages.  Here's the old version:

Screen Shot 2021-07-07 at 10 24 48 AM

This PR adds a background and card to make it visually distinct:

Screen Shot 2021-07-07 at 10 24 46 AM

This PR also removes the CTA footer from the docs pages

TODO:

- [x] Remove the CTA footer from /docs pages
- [x] Use a gradient for the background not an image so it matches the site better

### CODE REVIEW

**Comment by evantahler** [comment]
Unsplash license for reference - https://unsplash.com/license

**Comment by andyjih** [comment]
I'd rather we do this story: https://www.pivotaltracker.com/story/show/178634350

**Comment by evantahler** [comment]
I'm personally a fan of the CTA and want to keep it

**Comment by andyjih** [comment]
I'm strongly against it. I'd rather we make a persistent element like a fixed nav that has CTAs to trials. Than add a CTA footer to every page. 

Examples: 
https://stripe.com/docs/payments/integration-builder
https://docs.getdbt.com/docs/introduction

**Comment by teallarson** [comment]
> I'm strongly against it. I'd rather we make a persistent element like a fixed nav that has CTAs to trials. Than add a CTA footer to every page.
> 
> Examples:
> https://stripe.com/docs/payments/integration-builder
> https://docs.getdbt.com/docs/introduction

@andyjih can you share some more of your thinking/reasoning on this?  I'm interested to hear more.

**Review by andyjih — APPROVED** [review]
👍

**Review by teallarson — APPROVED** [review]

**Pull request merged**
