### PR TITLE
177009772 - update screenshots

### PR DESCRIPTION
**Pull request by teallarson**
DONE:
- homepage
- solutions pages
- specific plugins

I did not touch existing screenshots that showed our most recent UI, only ones that were out-of-date.

### CODE REVIEW

**Review by evantahler — COMMENTED** [review]
Looking better!

* Presumably on the homepage and solutions pages, we are following one profile (Hermione) though the system.  Can we show her info on `public/images/home/how-it-works-3.png` ? (currently Draco) 
* I don't imagine we have the rights to show a profile picture for her

Some of the new image's aspect ratios don't seem quite right (on /integrations/destinations/hubspot) 
Screen Shot 2021-08-26 at 3 19 15 PM

**Comment by teallarson** [comment]
Ah ha, they each have specific dimensions in the plugin info file.  Fixed!

**Comment by evantahler** [comment]
Almost there! looks like the `What` in the mailchimp screenshot is highlighed

**Comment by teallarson** [comment]
> Almost there! looks like the `What` in the mailchimp screenshot is highlighed

Noo!! Thanks for catching that.  Apologies.

**Pull request merged**
