### PR TITLE
chore: add the dev install/run on linux docs section.

### PR DESCRIPTION
**Pull request by pauloouriques**

### CODE REVIEW

**Comment by bleonard** [comment]
thanks!

**Comment by bleonard** [comment]
@pauloouriques it looks like you need to set up `prettier` (https://prettier.io) to run in your dev environment on save.
That's the test that is currently failing.

**Comment by evantahler** [comment]
Thanks @pauloouriques!  I ran the linter to get this passing and I'll merge it in!

**Comment by evantahler** [comment]
Also, I hid each OS' instructions behind a details block:

Screen Shot 2021-01-25 at 8 23 19 AM

**Pull request merged**
